# Generated by Django 5.1.7 on 2025-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("descriptio", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="about", verbose_name="Фото")),
            ],
            options={
                "verbose_name_plural": "Команда",
            },
        ),
    ]
