# Generated by Django 5.1.7 on 2025-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('awards', models.TextField(verbose_name='награды')),
                ('rewards1', models.TextField(verbose_name='признание 1')),
                ('rewards2', models.TextField(verbose_name='признание 2')),
                ('rewards3', models.TextField(verbose_name='признание 3')),
                ('rewards4', models.TextField(verbose_name='признание 4')),
                ('rewards5', models.TextField(verbose_name='признание 5')),
                ('rewards6', models.TextField(verbose_name='признание 6')),
                ('rewards7', models.TextField(verbose_name='признание 7')),
                ('rewards8', models.TextField(verbose_name='признание 8')),
            ],
            options={
                'verbose_name_plural': 'награды',
            },
        ),
    ]
