# Generated by Django 5.1.7 on 2025-03-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_recog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recog',
        ),
    ]
