# Generated by Django 5.1.7 on 2025-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='мотивируеший предложения')),
                ('text', models.TextField(verbose_name='что ты можешь предложить')),
            ],
        ),
    ]
