# Generated by Django 5.1.7 on 2025-03-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('text2', models.TextField(verbose_name='текст2')),
            ],
            options={
                'verbose_name_plural': 'Заголовок',
            },
        ),
    ]
