# Generated by Django 5.1.7 on 2025-03-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='контакт ')),
                ('desc1', models.TextField(verbose_name='описание')),
                ('desc2', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name_plural': 'контакт',
            },
        ),
    ]
