# Generated by Django 5.1.7 on 2025-03-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "image1",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 1"),
                ),
                (
                    "image2",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 2"),
                ),
                (
                    "image3",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 3"),
                ),
                (
                    "image4",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 4"),
                ),
            ],
            options={
                "verbose_name_plural": "Настройки Баннера",
            },
        ),
    ]
