# Generated by Django 5.1.7 on 2025-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="description_video",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Описание Видео"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_video",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовок Видео"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="url_video",
            field=models.URLField(default=1, verbose_name="Ссылка на видео"),
            preserve_default=False,
        ),
    ]
