# Generated by Django 5.1.7 on 2025-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_settings_description_video_settings_title_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="text",
            field=models.CharField(default=1, max_length=50, verbose_name="Текст"),
            preserve_default=False,
        ),
    ]
