# Generated by Django 5.1.7 on 2025-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_settings_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50, verbose_name="Текст")),
            ],
            options={
                "verbose_name_plural": "Текс",
            },
        ),
        migrations.RemoveField(
            model_name="settings",
            name="text",
        ),
    ]
