# Generated by Django 5.1.7 on 2025-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_text_remove_settings_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="image", verbose_name="Фото")),
                ("image2", models.ImageField(upload_to="image", verbose_name="Фото 2")),
            ],
            options={
                "verbose_name_plural": "Фото",
            },
        ),
    ]
